---
- fail: msg="Please set the 'uoc_user' variable"
  when: uoc_user is not defined

- name: Create default user
  become: true
  ansible.builtin.user:
    name: "{{ uoc_user }}"
    shell: /bin/bash
    groups: vboxsf
    append: yes

- name: Set authorized key from the current user
  ansible.posix.authorized_key:
    user: "{{ uoc_user }}"
    state: present
    key: "{{ item }}"
  with_items:
    - "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
    - "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: Allow user to sudo without password
  copy:
    src: sudoers
    dest: /etc/sudoers.d/{{ uoc_user }}

- name: Update APT cache
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 10800  # 3h
  changed_when: false

- name: Install basic packages
  become: true
  apt:
    name:
      - acl
      - git

- name: Install editor
  become: true
  block:
    - name: Install Vim
      apt:
        name: vim
        install_recommends: no
    - name: Install vimrc
      copy:
        src: vimrc.local
        dest: /etc/vim/vimrc.local

- name: Install login profile
  become: true
  copy:
    src: login.sh
    dest: /etc/profile.d/login.sh

- name: Install basic tools
  become: true
  apt:
    name:
      - git
