---
- name: Create default user
  become: true
  ansible.builtin.user:
    name: "{{ default_user }}"
    shell: /bin/bash
    groups: vboxsf
    append: yes

- name: Allow user to sudo without password
  copy:
    src: sudoers
    dest: /etc/sudoers.d/{{ default_user }}

- name: Update APT cache
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 10800 # 3h
  changed_when: false

- name: Install basic packages
  become: true
  apt:
    name:
      - acl
      - git

- name: Install editor
  become: true
  block:
    - name: Install Vim
      apt:
        name: vim
        install_recommends: no
    - name: Install vimrc
      copy:
        src: vimrc.local
        dest: /etc/vim/vimrc.local

- name: Install login profile
  become: true
  copy:
    src: login.sh
    dest: /etc/profile.d/login.sh
